server {
    listen 80;
    server_name dcmshriram.conformal.live;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name dcmshriram.conformal.live;

    ssl_certificate /etc/letsencrypt/live/dcmshriram.conformal.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dcmshriram.conformal.live/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 10M;

    location / {
        proxy_pass http://partner-dcmshriram:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_cache off;
    }
}
